planets:
  service:
    url: http://poc-keycloak-service-preprod:8091/planets

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak-preprod:8080/realms/bzhcamp}
        registration:
          keycloak:
            client-id: app-springboot
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak-preprod:8080/realms/bzhcamp}

logging:
  level:
    root: WARN
    com.zenika: INFO